#!/usr/bin/env bash
set -euo pipefail

# Resolve before cd: re-execing "$0" after changing directory only works when
# the script was invoked from the repository root. From inside scripts/, the
# relative path no longer points at anything.
self=$(readlink -f -- "$0")
cd "$(dirname -- "$self")/.."

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  exec sudo -- "$self" "$@"
fi

install -Dm755 scripts/asustorctl /usr/local/bin/asustorctl
install -Dm755 scripts/fanspeed /usr/local/bin/fanspeed
install -Dm755 scripts/cloud-nas-status /usr/local/bin/cloud-nas-status
install -Dm755 scripts/cloud-nas-sync-now /usr/local/bin/cloud-nas-sync-now
install -Dm755 scripts/cloud-nas-watch /usr/local/bin/cloud-nas-watch
install -Dm755 scripts/cloud-nas-progress /usr/local/bin/cloud-nas-progress
install -Dm755 scripts/nas-mount-migrate /usr/local/bin/nas-mount-migrate
install -Dm755 scripts/nas-status /usr/local/bin/nas-status
install -Dm755 scripts/nas-fand /usr/local/bin/nas-fand
install -Dm755 scripts/lcdline /usr/local/bin/lcdline
install -Dm755 scripts/nas-lcd-banner /usr/local/bin/nas-lcd-banner
install -Dm755 scripts/nas-leds /usr/local/bin/nas-leds
install -Dm755 scripts/m365-backup-lib /usr/local/bin/m365-backup-lib
install -Dm755 scripts/m365-backup-preflight /usr/local/bin/m365-backup-preflight
install -Dm755 scripts/m365-backup-inventory /usr/local/bin/m365-backup-inventory
install -Dm755 scripts/m365-backup-sync /usr/local/bin/m365-backup-sync
install -Dm755 scripts/m365-backup-status /usr/local/bin/m365-backup-status
install -Dm644 docs/m365-backup.md /usr/local/share/doc/asustor-nas-control/m365-backup.md
install -Dm644 docs/nas-status.md /usr/local/share/doc/asustor-nas-control/nas-status.md
install -Dm644 docs/thermal-and-lcd.md /usr/local/share/doc/asustor-nas-control/thermal-and-lcd.md
install -Dm644 systemd/m365-backup.service /etc/systemd/system/m365-backup.service
install -Dm644 systemd/m365-backup.timer /etc/systemd/system/m365-backup.timer

# The config is never overwritten: it carries the tenant and client IDs, and the
# path to a credential. Seed it once, then leave it alone on every later install.
if [[ ! -e /etc/m365-backup/m365-backup.conf ]]; then
  install -d -m 0700 /etc/m365-backup
  install -m 0600 scripts/m365-backup.conf.example /etc/m365-backup/m365-backup.conf
  seeded_conf=1
fi

printf 'Installed:\n'
printf '  /usr/local/bin/asustorctl\n'
printf '  /usr/local/bin/fanspeed\n'
printf '  /usr/local/bin/cloud-nas-status\n'
printf '  /usr/local/bin/cloud-nas-sync-now\n'
printf '  /usr/local/bin/cloud-nas-watch\n'
printf '  /usr/local/bin/cloud-nas-progress\n'
printf '  /usr/local/bin/nas-mount-migrate\n'
printf '  /usr/local/bin/nas-status\n'
printf '  /usr/local/bin/nas-fand\n'
printf '  /usr/local/bin/lcdline\n'
printf '  /usr/local/bin/nas-lcd-banner\n'
printf '  /usr/local/bin/nas-leds\n'
printf '  /usr/local/bin/m365-backup-lib\n'
printf '  /usr/local/bin/m365-backup-preflight\n'
printf '  /usr/local/bin/m365-backup-inventory\n'
printf '  /usr/local/bin/m365-backup-sync\n'
printf '  /usr/local/bin/m365-backup-status\n'
printf '  /etc/systemd/system/m365-backup.{service,timer}\n'
printf '\nTry:\n'
printf '  asustorctl status\n'
printf '  fanspeed 200\n'
printf '  nas-status\n'
printf '  cloud-nas-status\n'
printf '  cloud-nas-watch\n'
printf '  cloud-nas-progress\n'

# ProtectSystem=strict in the unit denies writes everywhere except ReadWritePaths.
# The destination is composed from variables, so resolve it the same way the
# library does and emit a drop-in, rather than asking anyone to keep a literal
# path in two places in step.
if [[ -r /etc/m365-backup/m365-backup.conf ]]; then
  # shellcheck source=/dev/null
  ( . /etc/m365-backup/m365-backup.conf
    base=${NAS_MOUNT_BASE:-/srv}
    vol=${NAS_M365_VOLUME:-NAS_03}
    sub=${M365_SUBDIR:-m365}
    dest=${M365_DEST_ROOT:-$base/$vol/$sub}
    install -d -m 0755 /etc/systemd/system/m365-backup.service.d
    cat >/etc/systemd/system/m365-backup.service.d/destination.conf <<EOF
# Generated by scripts/install.sh -- do not edit by hand.
# Regenerated from /etc/m365-backup/m365-backup.conf on every install.
[Service]
ReadWritePaths=${dest}
EOF
    printf '  /etc/systemd/system/m365-backup.service.d/destination.conf  (ReadWritePaths=%s)\n' "$dest"
  )
  systemctl daemon-reload 2>/dev/null || true
fi

# The tenant sync loop is a USER-level job, matching the existing OneDrive-Personal
# and GoogleDrive-Personal loops: it runs as the owner inside tmux under a user
# systemd unit, not as root. So it installs into that user's home, not /usr/local.
target_user=${SUDO_USER:-}
if [[ -n $target_user ]]; then
  target_home=$(getent passwd "$target_user" | cut -d: -f6)
  if [[ -n $target_home && -d $target_home ]]; then
    install -o "$target_user" -g "$target_user" -Dm755 \
      scripts/rclone-onedrive-da-sync-loop.sh \
      "$target_home/bin/rclone-onedrive-da-sync-loop.sh"
    install -o "$target_user" -g "$target_user" -Dm644 \
      systemd/user/onedrive-da-sync-tmux.service \
      "$target_home/.config/systemd/user/onedrive-da-sync-tmux.service"
    install -d -o "$target_user" -g "$target_user" -m 0700 "$target_home/.config/m365-backup"
    printf '  %s/bin/rclone-onedrive-da-sync-loop.sh\n' "$target_home"
    printf '  %s/.config/systemd/user/onedrive-da-sync-tmux.service\n' "$target_home"
  fi
else
  printf '  (SUDO_USER unset -- skipped the user-level tenant sync loop)\n'
fi

# ---------------------------------------------------------------------------
# Fan control and the front LCD
# ---------------------------------------------------------------------------
#
# Both are enabled here rather than merely installed. They exist because the
# board ships with no fan curve at all -- manual mode pinned at 20%, with the
# CPU sitting at 80 C -- and a NAS that boots without fan control is the
# problem this is meant to fix, not a state to leave someone to opt into.
#
# Fan control is set up FIRST and is insulated from everything after it. The
# LCD is a nicety; the fan is not, and no failure to create a group or reload
# udev may leave a box running uncooled.

install -Dm644 systemd/nas-fand.service /etc/systemd/system/nas-fand.service
install -Dm644 systemd/lcd-banner.service /etc/systemd/system/lcd-banner.service
install -Dm644 systemd/lcd-banner-refresh.service /etc/systemd/system/lcd-banner-refresh.service
install -Dm644 systemd/lcd-banner-refresh.timer /etc/systemd/system/lcd-banner-refresh.timer
install -Dm644 systemd/nas-leds.service /etc/systemd/system/nas-leds.service
install -Dm644 systemd/udev/99-asustor-lcm.rules /etc/udev/rules.d/99-asustor-lcm.rules

for conf_pair in "nas-fan:nas-fan.conf" "nas-lcd:nas-lcd.conf" "nas-leds:nas-leds.conf"; do
  conf_dir=/etc/${conf_pair%%:*}
  conf_file=$conf_dir/${conf_pair##*:}
  if [[ ! -e $conf_file ]]; then
    install -d -m 0755 "$conf_dir"
    install -m 0644 "scripts/${conf_pair##*:}.example" "$conf_file"
    printf '  %s  (seeded from the example)\n' "$conf_file"
  else
    printf '  %s already exists and was left untouched\n' "$conf_file"
  fi
done

systemctl daemon-reload 2>/dev/null || true

printf '\nFan control:\n'
if /usr/local/bin/nas-fand --check >/dev/null 2>&1; then
  if systemctl enable --now nas-fand.service 2>/dev/null; then
    # enable --now does not restart a unit that was already running, so an
    # upgrade would install a new binary and leave the old one regulating.
    systemctl try-restart nas-fand.service 2>/dev/null || true
    printf '  nas-fand.service enabled and running the installed build\n'
  else
    printf '  could not start nas-fand.service -- systemctl status nas-fand\n'
  fi
  sleep 1
  /usr/local/bin/nas-fand --status 2>/dev/null | sed -n '1,4p;/^hottest/p' | sed 's/^/  /'
else
  printf '  nas-fand --check FAILED; NOT enabling. Run it by hand to see why:\n'
  /usr/local/bin/nas-fand --check 2>&1 | sed 's/^/    /' || true
fi
printf '  stopping this service drives the fan to FULL on purpose; see the header of nas-fand\n'

# --- LCD, from here on: nothing below may abort the install ------------------

printf '\nFront LCD:\n'

# A system group, not uucp: uucp would hand over every serial device on the
# machine, including COM1 and any USB serial adapter plugged in later.
if ! getent group lcm >/dev/null; then
  if groupadd -r lcm 2>/dev/null; then
    printf '  group lcm created\n'
  else
    printf '  WARNING: could not create group lcm; the udev rule will not resolve it\n'
  fi
fi
if [[ -n ${SUDO_USER:-} ]]; then
  if id -nG "$SUDO_USER" 2>/dev/null | tr ' ' '\n' | grep -qx lcm; then
    printf '  %s is already in group lcm\n' "$SUDO_USER"
  elif usermod -aG lcm "$SUDO_USER" 2>/dev/null; then
    # -a is not optional: without it this replaces every other group the user
    # is in, wheel included, and takes their sudo with it.
    printf '  %s added to group lcm  (log in again, or run: newgrp lcm)\n' "$SUDO_USER"
  else
    printf '  WARNING: could not add %s to group lcm\n' "$SUDO_USER"
  fi
else
  printf '  SUDO_USER is unset, so no account was added to group lcm.\n'
  printf '  To drive the panel as yourself: usermod -aG lcm <user>\n'
fi

udevadm control --reload-rules 2>/dev/null || true
udevadm trigger --subsystem-match=tty --action=add 2>/dev/null || true

if [[ -e /dev/asustor-lcm || -e /dev/ttyS1 ]]; then
  if systemctl enable --now lcd-banner.service 2>/dev/null; then
    systemctl try-restart lcd-banner.service 2>/dev/null || true
    printf '  lcd-banner.service enabled and started\n'
  else
    printf '  could not start lcd-banner.service -- systemctl status lcd-banner\n'
  fi
  # Independent of the above: the later re-read matters most precisely when the
  # first write did not go well.
  systemctl enable --now lcd-banner-refresh.timer 2>/dev/null || true
  printf '  lcd-banner-refresh.timer enabled (re-reads the boot state 90s after boot)\n'
  /usr/local/bin/nas-lcd-banner --check 2>/dev/null | sed -n '1,4p' | sed 's/^/  /' || true
else
  printf '  no LCD serial port present; skipped\n'
fi

printf '\nFront-panel LEDs:\n'
if systemctl enable --now nas-leds.service 2>/dev/null; then
  systemctl try-restart nas-leds.service 2>/dev/null || true
  printf '  nas-leds.service enabled; hardware blink cleared, status LED solid\n'
else
  printf '  could not start nas-leds.service -- systemctl status nas-leds\n'
fi

printf '\nMicrosoft 365 mirror (read docs/m365-backup.md first):\n'
if [[ ${seeded_conf:-0} -eq 1 ]]; then
  printf '  1. edit /etc/m365-backup/m365-backup.conf   # seeded from the example\n'
else
  printf '  1. /etc/m365-backup/m365-backup.conf already exists and was left untouched\n'
fi
printf '  2. printf %%s SECRET > /etc/m365-backup/client_secret && chmod 400 it\n'
printf '  3. m365-backup-preflight                    # read-only, safe to run blind\n'
printf '  4. m365-backup-inventory\n'
printf '  5. m365-backup-sync --dry-run\n'
printf '  6. systemctl daemon-reload && systemctl enable --now m365-backup.timer\n'

printf '\nDang & Associates tenant sync (user-level, matches the Personal loops):\n'
printf '  1. put tenant + client id in ~/.config/m365-backup/m365-backup.conf\n'
printf '  2. printf %%s SECRET > ~/.config/m365-backup/client_secret && chmod 600 it\n'
printf '  3. rclone-onedrive-da-sync-loop.sh --once      # one cycle, in the foreground\n'
printf '  4. systemctl --user enable --now onedrive-da-sync-tmux.service\n'
