#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  exec sudo -- "$0" "$@"
fi

install -Dm755 scripts/asustorctl /usr/local/bin/asustorctl
install -Dm755 scripts/fanspeed /usr/local/bin/fanspeed
install -Dm755 scripts/cloud-nas-status /usr/local/bin/cloud-nas-status
install -Dm755 scripts/cloud-nas-sync-now /usr/local/bin/cloud-nas-sync-now
install -Dm755 scripts/cloud-nas-watch /usr/local/bin/cloud-nas-watch
install -Dm755 scripts/cloud-nas-progress /usr/local/bin/cloud-nas-progress
install -Dm755 scripts/nas-mount-migrate /usr/local/bin/nas-mount-migrate
install -Dm755 scripts/nas-status /usr/local/bin/nas-status
install -Dm755 scripts/m365-backup-lib /usr/local/bin/m365-backup-lib
install -Dm755 scripts/m365-backup-preflight /usr/local/bin/m365-backup-preflight
install -Dm755 scripts/m365-backup-inventory /usr/local/bin/m365-backup-inventory
install -Dm755 scripts/m365-backup-sync /usr/local/bin/m365-backup-sync
install -Dm755 scripts/m365-backup-status /usr/local/bin/m365-backup-status
install -Dm644 docs/m365-backup.md /usr/local/share/doc/asustor-nas-control/m365-backup.md
install -Dm644 docs/nas-status.md /usr/local/share/doc/asustor-nas-control/nas-status.md
install -Dm644 systemd/m365-backup.service /etc/systemd/system/m365-backup.service
install -Dm644 systemd/m365-backup.timer /etc/systemd/system/m365-backup.timer

# The config is never overwritten: it carries the tenant and client IDs, and the
# path to a credential. Seed it once, then leave it alone on every later install.
if [[ ! -e /etc/m365-backup/m365-backup.conf ]]; then
  install -d -m 0700 /etc/m365-backup
  install -m 0600 scripts/m365-backup.conf.example /etc/m365-backup/m365-backup.conf
  seeded_conf=1
fi

printf 'Installed:\n'
printf '  /usr/local/bin/asustorctl\n'
printf '  /usr/local/bin/fanspeed\n'
printf '  /usr/local/bin/cloud-nas-status\n'
printf '  /usr/local/bin/cloud-nas-sync-now\n'
printf '  /usr/local/bin/cloud-nas-watch\n'
printf '  /usr/local/bin/cloud-nas-progress\n'
printf '  /usr/local/bin/nas-mount-migrate\n'
printf '  /usr/local/bin/nas-status\n'
printf '  /usr/local/bin/m365-backup-lib\n'
printf '  /usr/local/bin/m365-backup-preflight\n'
printf '  /usr/local/bin/m365-backup-inventory\n'
printf '  /usr/local/bin/m365-backup-sync\n'
printf '  /usr/local/bin/m365-backup-status\n'
printf '  /etc/systemd/system/m365-backup.{service,timer}\n'
printf '\nTry:\n'
printf '  asustorctl status\n'
printf '  fanspeed 200\n'
printf '  nas-status\n'
printf '  cloud-nas-status\n'
printf '  cloud-nas-watch\n'
printf '  cloud-nas-progress\n'

# ProtectSystem=strict in the unit denies writes everywhere except ReadWritePaths.
# The destination is composed from variables, so resolve it the same way the
# library does and emit a drop-in, rather than asking anyone to keep a literal
# path in two places in step.
if [[ -r /etc/m365-backup/m365-backup.conf ]]; then
  # shellcheck source=/dev/null
  ( . /etc/m365-backup/m365-backup.conf
    base=${NAS_MOUNT_BASE:-/srv}
    vol=${NAS_M365_VOLUME:-NAS_03}
    sub=${M365_SUBDIR:-m365}
    dest=${M365_DEST_ROOT:-$base/$vol/$sub}
    install -d -m 0755 /etc/systemd/system/m365-backup.service.d
    cat >/etc/systemd/system/m365-backup.service.d/destination.conf <<EOF
# Generated by scripts/install.sh -- do not edit by hand.
# Regenerated from /etc/m365-backup/m365-backup.conf on every install.
[Service]
ReadWritePaths=${dest}
EOF
    printf '  /etc/systemd/system/m365-backup.service.d/destination.conf  (ReadWritePaths=%s)\n' "$dest"
  )
  systemctl daemon-reload 2>/dev/null || true
fi

# The tenant sync loop is a USER-level job, matching the existing OneDrive-Personal
# and GoogleDrive-Personal loops: it runs as the owner inside tmux under a user
# systemd unit, not as root. So it installs into that user's home, not /usr/local.
target_user=${SUDO_USER:-}
if [[ -n $target_user ]]; then
  target_home=$(getent passwd "$target_user" | cut -d: -f6)
  if [[ -n $target_home && -d $target_home ]]; then
    install -o "$target_user" -g "$target_user" -Dm755 \
      scripts/rclone-onedrive-da-sync-loop.sh \
      "$target_home/bin/rclone-onedrive-da-sync-loop.sh"
    install -o "$target_user" -g "$target_user" -Dm644 \
      systemd/user/onedrive-da-sync-tmux.service \
      "$target_home/.config/systemd/user/onedrive-da-sync-tmux.service"
    install -d -o "$target_user" -g "$target_user" -m 0700 "$target_home/.config/m365-backup"
    printf '  %s/bin/rclone-onedrive-da-sync-loop.sh\n' "$target_home"
    printf '  %s/.config/systemd/user/onedrive-da-sync-tmux.service\n' "$target_home"
  fi
else
  printf '  (SUDO_USER unset -- skipped the user-level tenant sync loop)\n'
fi

printf '\nMicrosoft 365 mirror (read docs/m365-backup.md first):\n'
if [[ ${seeded_conf:-0} -eq 1 ]]; then
  printf '  1. edit /etc/m365-backup/m365-backup.conf   # seeded from the example\n'
else
  printf '  1. /etc/m365-backup/m365-backup.conf already exists and was left untouched\n'
fi
printf '  2. printf %%s SECRET > /etc/m365-backup/client_secret && chmod 400 it\n'
printf '  3. m365-backup-preflight                    # read-only, safe to run blind\n'
printf '  4. m365-backup-inventory\n'
printf '  5. m365-backup-sync --dry-run\n'
printf '  6. systemctl daemon-reload && systemctl enable --now m365-backup.timer\n'

printf '\nDang & Associates tenant sync (user-level, matches the Personal loops):\n'
printf '  1. put tenant + client id in ~/.config/m365-backup/m365-backup.conf\n'
printf '  2. printf %%s SECRET > ~/.config/m365-backup/client_secret && chmod 600 it\n'
printf '  3. rclone-onedrive-da-sync-loop.sh --once      # one cycle, in the foreground\n'
printf '  4. systemctl --user enable --now onedrive-da-sync-tmux.service\n'
